### ISSUE TITLE
[작업3] 구독하기 페이지 UI 개발

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/sooljaru#14]
https://sooljaru.com/subscription-dev 에  박스 선택 부분 우선 이미지로 올려놨는데요. 
1박스 / 2박스 선택을 해서 하단에 정기구독 버튼 결제 적용할 때 옵션 값으로 같이 보내려고 합니다. 기술적인 부분은 썬에게 한 번 더 검토하세요.

[디자인 추가 예정]
- 최 상단에 가격비교 및 설명부분을 추가한다고 하네요. (10/30 내용 도착)
- 다른 요청으로 해당 영역을 열거나, 닫는 버튼을 추가할 수 있습니다. (10/30 내용 도착)

**Comment by woonjjang** [comment]
```
<div class="cf01">
      <input type="radio" name="sub_box01" id="sub_box01_01" checked="checked"/>
    <label for="sub_box01_01">
	  <strong>1박스</strong>
	  <b>39,000</b>
	  <span>술자루 구독박스 1박스를 구독합니다. 한 박스에는 3병이 포함되어 있습니다.</span>
	  <i aria-hidden="true" class="fa fa-dot-circle-o"></i>
  	</label>
    <input type="radio" name="sub_box01" id="sub_box01_02"/>
      <label for="sub_box01_02">
	  <strong>2박스</strong>
	  <b>78,000</b>
	  <span>술자루 구독박스 2박스를 구독합니다. 한 박스에는 3병이 포함되어 있습니다.</span>
		<i aria-hidden="true" class="fa fa-dot-circle-o"></i>
  	</label>
</div>
```

**Comment by woonjjang** [comment]
고생하셨습니다.

**Comment by woonjjang** [comment]
![스크린샷 2020-11-02 오후 1 24 33](https://user-images.githubusercontent.com/6022883/97829997-f3163a80-1d0e-11eb-9ca9-21165cd96f75.png)

@css3studio 
초기에는 정기구독만 가능한 상태로 넣고, 개발이 완료되면 지금 화면 처럼 1박스구입 / 정기구독을 넣을 예정입니다. 현재 퍼블리싱 해 준 것에서 2박스 이상(선택 없는 박스) 부분만 업데이트 해 주시면 수정하면서 써 보겠습니다.

**Comment by woonjjang** [comment]
1) 구독 페이지에서 제일 상단에 위치해야 하는 건 정기구독입니다. 
2) 한박스 구입 -> '1회 구매'
3) 2박스 이상 전화문의 -> 이건 박스로 들어가는 게 좀 어색한 것 같습니다. 박스 없이 공지하는 걸로 마무리 하고 싶습니다. 
4) 한박스 구입의 경우 클릭했을 때 계좌번호를 바로 복사 하게 하는 기능 추가가 가능한지 문의드립니다.

**Comment by css3studio** [comment]
작업완료하였습니다

**Comment by woonjjang** [comment]
@css3studio 고생하셨습니다. 
@sunparty 하단에 사용하던 버튼과 1박스 구입 선택지를 누를 때도 카드창이 열리도록 추가가 필요합니다.
