### ISSUE TITLE
[버그] 아임웹 이슈로 보임 -PC/모바일로 사이트에 접속 할 때, 약간 흐릿했다가 다시 맑아지는 현상

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/sooljaru#17]
[고객]
 - 현재 PC/모바일로 사이트에 접속 할 때, 약간 흐릿했다가 다시 맑아지는 현상이 발견되고 있습니다.이 부분에 대한 확인도 추가로 부탁드리겠습니다. 

[그 외에 번쩍임 효과가 가끔 있음]
- 슬라이드 영역은 효과를 조절할 수 있어서, 그 전 테스트 화면 때문에 나올 수 있음. 
- https://sooljaru.com/subscription 상단 nav 메뉴가 항상 늦게 뜨는 문제 (아임웹에서 구현하면 거의 다 이런 문제가 있더라구요.)

증상확인만 부탁드려요. 
긴급하지 않습니다.

**Comment by css3studio** [comment]
음...이게 문제라고 여기는건가요...

**Comment by woonjjang** [comment]
지난주에 온 적이 있어서 ㅎㅎ
제가 한 번 더 확인은 할께요.  / 메뉴 부분은 방법이 있으면 대응하면 좋을 듯 (아임웹 / 캠페이너스) 로 납품하면 계속 이런 문제가 있을 수도...
