### ISSUE TITLE
[로그인 후] 회원 정보 보여주는 페이지

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/sooljaru#19]
1) home에서 로그인 / 로그아웃 버튼 hidden 좀 부탁드릴께요. 메뉴쪽에 넣어놨다가 기본 기능으로 교체했어요. 다른 페이지에서는 노출되도 됩니다. 
2) https://sooljaru.com/shop_mypage/ 페이지 왼쪽 메뉴에서 1:1문의 / 정보수정 / 회원탈퇴 부분만 남기고 안 보이도록 처리해 주시면 됩니다.

![스크린샷 2020-11-02 오후 6 58 19](https://user-images.githubusercontent.com/6022883/97855556-3d62e000-1d3e-11eb-88ff-da1f6c1d706d.png)

**Comment by woonjjang** [comment]
"누적 구매금액: 0원" / 쿠폰0" 영역도 지울 수 있다면 노출 안 되도록 처리 해 주시면 감사하겠습니다.

**Comment by css3studio** [comment]
마이페이지 버튼을 누르면, https://sooljaru.com/shop_mypage/?m2=qna 으로 이동하도록 가능한가요?

**Comment by css3studio** [comment]
먼저 헤더영역에 마이페이지 버튼을 추가해 넣어주세요~

**Comment by woonjjang** [comment]
https://sooljaru.com/shop_mypage 헤더 영역에 넣었어요. 
https://sooljaru.com/shop_mypage/?m2=qna 으로 이동가능하진 않습니다.

**Comment by woonjjang** [comment]
@css3studio 모바일에서도 확인 부탁드려요

**Comment by woonjjang** [comment]
@css3studio 탈퇴도 감춰주시면 감사하겠습니다.

**Comment by woonjjang** [comment]
1. 감춰야 하는 메뉴 생성되어 home에서 hidden 필요
2. 마이페이지에서 탈퇴 도 감춰주세요. 

@css3studio
