### ISSUE TITLE
미팅 및 디자인 레퍼런스 준비

### ISSUE THREAD

**Issue by calvin-design** [team-durumi/sooljaru#5]
[디자인자료]
- 로고
- 레퍼런스

[레퍼런스 조사 - 사이트]
- 고객 전달자료(1차)
- 별도 조사 자료(2차)

[레퍼런스]
- https://www.openpath.kr/

[고객미팅]
- 온라인으로 진행될 수 있다. 
- 자료를 많이 준비해간다.

**Comment by woonjjang** [comment]
From 로고 디자이너

안녕하세요.



사이트와 로고가 결합된 레퍼런스 찾아 전달드립니다.

모바일 베이스 사이트이기에 핸드폰으로 확인 부탁드리겠습니다.



모바일 사이트에서 로고의 활용은 크게 3가지로 나뉘는 것 같습니다.



1. 배경색과 로고의 합성형: 스크롤에 따라 배경이 움직이며, 로고는 배경과 자연스럽게 합성된 형태로 나타나는 형태



프란츠: http://www.franz.kr/

음악과 관련된 일상적인 사진에 자연스럽게 결합된 로고. 스크롤을 내리면 로고 뒤에 자연스럽게 흰색 바가 생긴다.



유후: http://yoohuu.kr/

로고 좌측상단 고정 형태. 스크롤에 따라 사진이 변경되기 때문에 로고는 블랙으로 고정.



스튜디오 알트: https://alt-works.com/




키 컬러, 로고 고정형. 사진에 로고가 가려지는지 여부에 무관하게 키컬러와 로고가 고정되어 있어 무심하고 쿨(?)한 느낌.





2. 상단고정형: 흰색 바와 메뉴가 상단에 고정되어있는 형태. 사진이 변경되어도 로고가 또렷하게 보인다는 장점이 있음.



그라더스: https://m.grds.com/

로고 고정형. 흰색의 바와 로고가 고정되어 있으며, 사진 위에 타이포그래피만 합성한 사이트. 모바일 사이트에 익숙하지 않은 사람도 쉽게 볼 수 있는 것이 장점.



펠트 커피: https://m.feltcoffee.com

로고 고정형 사이트: 로고는 상단에 고정되어 있는 형태. 

 

3. 플렉서블 (배경색에 따라 색상 변경)



투카타: http://m.tukata.kr/

인형 판매 쇼핑몰. 사진의 색상에 따라 로고의 색상(흑백)이 바뀌는 플렉서블 스타일. (모바일에서 스크롤을 내려 확인해보세요)





기타: 키컬러의 활용



일상직물:  https://www.isjm.kr/

미색의 배경에 키 컬러인 녹색 로고를 활용한 사이트. 좌측 상단의 메뉴를 누르면 키컬러인 녹색의 메뉴바가 나오는 것이 특징. (키컬러의 활용에 참고)







이상입니다.



개인적으로는 사진에 로고가 붙는 느낌보다 로고 상단 고정형 + 사진에 타이포그래피가 합성된 그라더스 사이트의 예시가 좋아보이는데요.



술자루의 경우 기본형 로고는 흑백(노란 동그라미 없는 버전) 이되, 새로고침 할 때마다 로고 뒤의 형태와 색상이 변경되는 디자인을 적용하면 멋질 것 같습니다. (상단고정형 + 플렉서블 로고)



여러가지 사이트 비교해보시고 의견 부탁드리겠습니다.



감사합니다.



김호 드림

**Comment by woonjjang** [comment]
https://vimeo.com/249136032

레퍼런스 영상이에요~

**Comment by woonjjang** [comment]
[논의]
1. 하단에 메뉴바가 있기 때문에 상단을 고정할 필요는 없음 그라더스: https://m.grds.com/ 페이지 처럼 블랙,white, gray를 활용한 로고를 사용함.
2. 로고에 결정된 키컬러와 영상(vimeo 이미지) 사진에서 나오는 이미지를 활용해서 버튼이 부각된 스타일로 시안을 잡는다. 

[figma] 작업을 하면서

1. 콘텐츠 목록, 프로모션 목록 부분은 초기에 오픈 안 하더라도 디자인을 잡아놔야 할 것으로 보임.

**Comment by woonjjang** [comment]
@calvin-design 시안 뽑는데 모자라는 자료가 있을 텐데, 확인하고 점심 먹고 콜 한 번 나눠요 ~ 필요한 것들 한 번더 목록으로 찍어주면 감사하겠습니다.
