### ISSUE TITLE
[구독부분의 결제] 기술 이슈

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/sooljaru#6]
[고객이 하고 싶어하는 부분]
<img width="852" alt="스크린샷 2020-09-08 오후 4 53 29" src="https://user-images.githubusercontent.com/6022883/92448964-50e94300-f1f4-11ea-91aa-77154e57e676.png">

[결제폼]
- 결제폼을 만들어서 아임웹에 삽입 
- 해당 결제 부분을 처리할 때 사용자 정보 및 결제 정보를 iamport 쪽으로 전달함. 
- 구독관리 및 처리를 iamport 관리자쪽에서 처리함. 

[결제 처리]
-  즉시 결제가 아닌 지정된 날짜에 결제처리가 되는 방식을 원함. (정기결제)
- https://admin.iamport.kr/  or https://admin.bootpay.co.kr/receipt?s=1 결제모듈 api가 잘 처리되어 있는 곳에서 제공하는 결제 관리자와 모듈열결을 사용하고 구독신청 및 결제정보를 받는 영역 처리를 한다. 

[이슈]
1) 결국은 rails같은 모델로 user_id 를 개발 해 놓고, 결제, 배송방식, 회원정보 수정시에 변경요청을 처리해 줄 수 있어야 하지 않을까
2) 1번 이슈를 좀 더 풀어서 설명하자면 imweb에서 회원로그인, 18세인증처리, 마이페이지가 있어도 iamport 쪽에 저장한 정보를 마이페이지에 뿌려줄 수 없는 이슈가 있어서 결제창 외에 마이페이지, 회원로그인까지 imweb을 벗어나는게 아닐까 해서
3) 여러 PG사의 정기결제솔루션을 제공하는 연차가 쌓잏 서비스를 먼저 써 보는게 좋을 듯 함. https://github.com/iamport/iamport-manual/blob/master/%EB%B9%84%EC%9D%B8%EC%A6%9D%EA%B2%B0%EC%A0%9C/README.md

**Comment by woonjjang** [comment]
@mozodev @sunparty 이슈 부분 의견 좀 주시면 감사하겠습니다.

**Comment by mozodev** [comment]
아임포트같은 결제대행 서비스를 이용하면 일단 아임웹을 벗어나는게 맞습니다.
이게 고객에게 용납이 안되면 프로젝트를 드롭하시면 되겠습니다.

검색이라는걸 좀 해보면...
https://imweb.me/notice?view&page=4&419

> 내가 만든 쇼핑몰에 정기결제 되면 좋겠어요! 언제 돼요?
고객분들이 많이 기다리셨던 쇼핑몰 정기결제 기능은
올해 연말 제공을 위해 PG사와 협의 중입니다.
조금만 기다려 주세요! 열심히 노력하고 있습니다.

운짱 상황에서 고객과 대화할 수 있는 포인트는 여기가 지원 준비중이라니 
저게 될때까지는 단품만 파는 방향으로 가고 지원하면 바로 달아줄께...

이렇게 설득이 안되면 저도 모르겠습니다. 그냥 카페24쇼핑몰이든... 
고도몰이든 되는 솔루션을 사서 하시는게...

@sunparty 
졸라 힘들텐데 레일즈로 쇼핑몰 한번 만들어볼 의향이 있으면 그렇게 진행해보도록 하죠 ㅎ

**Comment by mozodev** [comment]
일반적인 단건결제는 거의 이슈가 없어보입니다. 
제 아내가 쇼핑몰 운영하는걸 보니... 
컴맹에, 알고 싶은 욕구도 없는... 전형적인 사람인데
큰 문제 없이 잘 팔고 배송도 잘 하고 있...

**Comment by woonjjang** [comment]
고객은 구독에 집중하고 싶어하는 상황이라 아임포트 제안은 수용할꺼에요. 단품파는 것을 더 지양하는 상태라서 둘 다 운영할 수도 있는 상황
- (imweb)메인관리, 콘텐츠 편집(게시판 편집), 프로모션 페이지
- (import)구독정보 입력, 결제, id값으로 구독정보 변경이랑 확인 + import 관리자

@mozodev  아임포트가 붙으면 결국 레일즈든, php든 application 영역이 반드시 필요하겠죠 ?

**Comment by woonjjang** [comment]
>> 아임포트같은 결제대행 서비스를 이용하면 일단 아임웹을 벗어나는게 맞습니다. 
답해주신게 있긴 했네요. ㅎㅎ

-실제로 기타 콘텐츠관리, 아이템 관리 등등 할 요소가 많은데, 그걸 모두 레일즈로 뜨는 것은 가격이나 방식이나 모두 안 맞는 상태라서 저도 드랍생각을 하고 있긴 했죠.

**Comment by mozodev** [comment]
결제 기능만 아임포트에 의지하게 되는거죠..
로그인해서 자기 주소 자동으로 들어가고 이런건 아임웹에서 제공해주고 있기 때문에..
아임웹이 정기결제를 지원하는게 가장 일을 쉽게하는 방법인 듯 합니다.

잘게 쪼개서 일을 더 복잡하게 만들 수 있는데 그럼 안하는게 나은 듯...

그리고 아임포트보다는 부트페이가 더 모던한 듯...
https://www.bootpay.co.kr/

**Comment by suncrud** [comment]
쇼핑몰은 개발도 개발인데 운영이 엄청 인생이 힘들어질 거 같은 생각이 드네요.. 
요기 모조님이 말씀해주신대로 설득을 해보는게 플랜A 같구 

> 아임포트같은 결제대행 서비스를 이용하면 일단 아임웹을 벗어나는게 맞습니다.
> 이게 고객에게 용납이 안되면 프로젝트를 드롭하시면 되겠습니다.
> 
> 검색이라는걸 좀 해보면...
> https://imweb.me/notice?view&page=4&419
> 
> > 내가 만든 쇼핑몰에 정기결제 되면 좋겠어요! 언제 돼요?
> > 고객분들이 많이 기다리셨던 쇼핑몰 정기결제 기능은
> > 올해 연말 제공을 위해 PG사와 협의 중입니다.
> > 조금만 기다려 주세요! 열심히 노력하고 있습니다.
> 
> 운짱 상황에서 고객과 대화할 수 있는 포인트는 여기가 지원 준비중이라니
> 저게 될때까지는 단품만 파는 방향으로 가고 지원하면 바로 달아줄께...
> 
> 이렇게 설득이 안되면 저도 모르겠습니다. 그냥 카페24쇼핑몰이든...
> 고도몰이든 되는 솔루션을 사서 하시는게...
> 
> @sunparty
> 졸라 힘들텐데 레일즈로 쇼핑몰 한번 만들어볼 의향이 있으면 그렇게 진행해보도록 하죠 ㅎ

마조키스트는 아니지만.. 그에 상응하는 대가가 오면... 과연 올까요? ㅋㅋ

**Comment by suncrud** [comment]
부트페이는 매우 깔쌈해보이네요 ㅎㅎ 그에 상응하는 대가가 온다면 써봐야겠어요 ^0^

**Comment by woonjjang** [comment]
정기결제 파라미터들 못 봤었는데, bootpay도 괜찮아 보이네요. 
오늘 사당에서 만나서 정리해서 오겠습니다.

**Comment by woonjjang** [comment]
[논의 사항]
1. 새로 아임웹에서 구독결제(정기결제) 기능을 넣어주는 시점(내년 초반)에 부트페이로 갈아타든, 별도 시스템으로 개발하든 선택
2. 부트페이지에서 결제를 관리하는 방식으로 가고, 로그인 연결과 마이페이지 부분을 포기하고 간다. 
3. 레일즈로 부트페이 구독결제 연결하는 부분


[기술부분]
1. 로그인 된 사용자 정보를 구독결제 페이지쪽으로 넘기지 않아도 된다. (사이트에 와서 구독 결제 부분 링크를 로그인 사용자만 누를 수 있도록 함.)
2. 마이페이지 부분의 정보를 연결하지 않아도 된다. 
3. 프로세스 및 wireframe : https://www.figma.com/file/ONSOMBhtz3t4BbHiMKZwDO/wireframe-and-process?node-id=88%3A0
4. 우리도 결제 붙이는 일이 있을 때 부트페이쪽으로 해 보면 어떨까 함. (durumi-ops 계정 하나 만들어 놨음. PG사 연결전에 테스트 할 수 있음)

결론은 한 번 해 봅시다. @mozodev @sunparty 
낼 자세히 설명드릴께요.

**Comment by woonjjang** [comment]
논의 : https://github.com/team-durumi/sooljaru/issues/7
