### ISSUE TITLE
[구독 결제] 정기결제 구현

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/sooljaru#7]
[아임웹]
- 빠르게 KG 이니시스 승인 처리를 받는다. (아이템 5개 등록 및 결제)
- KG 이니시스로 5개 아이템 등록해서 결제를 진행한다. (안 되더라도 12월 이후에 결제를 처리할 수 있으므로)
- 테스트는 할 수 있으니깐, PG사 심사가 처리 되어야 한다. 

[아임웹 로그인]
- ajax로 해당되는 데이터를 찾아서 주소로 던진다. 
- 회원 고유 ID(마이페이지에서 확인) 한 값으로 처리해서 스크립트로 해당 값 / 파라미터를 부트페이(아임포트)로 전달한다. (IDX)

[아임웹]
- KG 이니시스로 5개 아이템 등록해서 결제를 진행한다. (안 되더라도 12월 이후에 결제를 처리할 수 있으므로)
- 회원 고유 ID(마이페이지에서 확인) 한 값으로 처리해서 스크립트로 해당 값 / 파라미터를 부트페이(아임포트)로 전달한다. (IDX)

[이슈]
- 주소 부분이나 데이터 부분은 엑스트라 필드로 처리한다. (부트페이)
- ID값이든 동일한 값을 PG사(부트페이) 엑서 다운로드, 회원값이랑 매칭해서 엑셀을 매칭해서 사용한다.

**Comment by woonjjang** [comment]
[테스트 및 진행을 위해 필요한 것]
아임웹 PG 연결은 NICE Pay / 부트페이는 NHN KCP 를 연결합니다. 
두 가지 모두 심사가 필요해서, 디자인이 다 되고 시작하면 시간을 낭비할 것 같아서, 아임웹 만든 것으로 심사를 받으려고 합니다. 
그래야 여러가지 옵션으로 어떻게 사용할지 테스트할 여유가 있고, 10월을 맞이할 것으로 보입니다. 

### 1. 기본 정보
- [x] (테스트아이디) tester@sooljaru.com / test1234
>> 관련해서 해당 술자루 imweb 쇼핑몰은 팀 두루미 리셀러 관리 페이지에 가도 확인이 가능함.
- [x]  https://sooljaru-02.imweb.me/
- [x] 도메인은 고객이 아임웹 카드 결제, 선납을 하면 sooljaru.com 으로 진행하려고 함. (경로 변경)
- [ ] 주조장 홈페이지나 자료를 통해서 5개 아이템 자료가 필요함(쇼핑몰 승인)
- [x] 19세 결제 연결 
- [x] 더미 아이템
- [x] 통신판매번호(금요일 - 월) 승인 진행


### 2. 아임웹 PG 연결
https://imweb.me/faq?mode=view&category=29&category2=39&idx=71419
- 상품 5개가 등록되어 있는게 필요할 것 같아요.(가짜 아이템 필요합니다. - 사진 간단한 내용)
- 올해가 지난이후에 구독기능이 생겼을 때, 아임웹 PG로 연결 진행 
- 아임웹 PG 연결은 NICE Pay

### 3. 부트페이 PG 연결 (NHN KCP -> Pay app rest-api 로 변경)
- [x] 술자루 계정생성 완료.([vault](https://docs.google.com/document/d/1RB3GAEJ_JqipTY_U3bDDfyHMPiuucLJ6cYdHnKz1BQ4/edit))
- [x] 결국 심사를 받아야함. 
- [x] Pay app (심사 시작)

### 4. 부트페이 PG 연결 (페이앱)

일단 페이앱은 REST API로 카드 정보를 전달하면, 빌링키를 가져와서 결제할 수 있는 형태입니다.
카드 입력창을 Custom 할 수 있는 장점이 있고, 카드 정보만 REST API로 보내면 받아올 수 있다는 장점이 있습니다.

단점은 카드 정기결제는 REST API 진행되기 때문에 동의창이 없으나 다른 결제에 페이앱 동의창 -> PG사 동의창 -> 결제 와 같은 앞에 페이앱 동의창이 하나 더 붙는 불편함이 있습니다.

### 3. 부트페이 PG 연결-카드 정기결제 (NHN KCP)

KCP 역시 카드 정기결제를 지원합니다. 단, 페이앱과 같이 REST API 형태로 카드 정보를 받아서 빌링키를 받아오는 형태가 아니라
KCP에서 제공하는 카드 입력창을 통해 빌링키를 가져오는 방식입니다.

KCP 카드 정기결제의 단점은 

1) 공인인증서를 통한 인증 과정이 있음 - [ 일부 가맹점은 없을 수 있습니다. 하지만 대부분의 가맹점이 인증이 붙어서 나오게 됩니다. ]
2) 결제창 커스텀이 불가능함

이렇게 크게 2가지가 있습니다.

KCP 카드 정기결제 가맹은 일반 가맹과 동일하게 최소 2주~최대 1달까지 소요됩니다.
다만, 다른 PG와 다르게 카드 정기결제 심사가 까다로운편이고 업종에 따라 제한이 있을 수 있습니다. 
KCP 가맹을 희망하시는 경우, 업종에 따른 제한여부는 KCP에 문의해서 저희가 별도로 알려드릴 수 있습니다.

**Comment by woonjjang** [comment]
회원가입 설정에 사용자 정의항목으로 해당 필드를 추가하거나 넣을 수 있음. ![스크린샷 2020-09-21 오후 6 09 37](https://user-images.githubusercontent.com/6022883/93752502-b815e700-fc39-11ea-8634-4a748bb8e5cc.png)

**Comment by woonjjang** [comment]
행정적인 절차랑 Deadline 변경(10.15)으로 dd 이슈들 먼저 정리하고 정기결제 이슈 봐도 될 듯 요 ~  @mozodev @sunparty 
http://sooljaru.com/ 도메인 붙였습니다.

**Comment by mozodev** [comment]
헤더가 너무 어두워서 답답한 듯한데요... 
로고타입 그대로 두고 배경만 투명으로 가면 좋을 듯 ㅎ

**Comment by woonjjang** [comment]
살짝 조정했습니다. 
민수씨가 시안을 2개 잡고 있어서, 현재 술자루홈은 다른 버전으로 화면을 잡고 있어요. (시안 겹칠까봐)

**Comment by woonjjang** [comment]
@mozodev 
PAYAPP 승인 나서 해당 계정을 입력해 두었습니다. 
PAYAPP 실 계정사용에는 아이디 / link_val  /link_key  3개 값을 고객으로 부터 받아서 입력 / 저장해 두었음. 
사용하는 카드로 3000원 실제 결제했을 때 결제 승인이 떨어짐.  - 페이앱 내부(페이앱에서 결제상점 정보를 변경해야 할 것으로 보임 - (주)유디아이디 페이앱 사업자로 결제가 떨어짐)

1) 아임웹쪽 테스트 페이지(로그인이 되어야 페이지에 접근할 수 있도록 해 놓았음) : http://sooljaru.com/subscription
- 회원가입 / 로그인 / 성인인증을 마친 사용자가 서비스내에서 구독하기 버튼을 누른다. 

2) 페이앱 결제 쪽으로 정보를 전달한다. (정기결제)
- 페이앱에 사용비밀번호 / 카드정보를 등록해야 결제를 사용할 수 있음.

**Comment by suncrud** [comment]
1. 유저정보를 긁어서 부트페이에 넘긴다. 
2. 부트페이 콜백 받아서 처리 
 - lambda 등으로 빌링키 (+ 유저정보 ) db에 저장 
 - cronjob 으로 정기결제 구현 .

**Comment by woonjjang** [comment]
https://github.com/team-durumi/sooljaru_api

**Comment by woonjjang** [comment]
@sunparty 고생하시고, 저녁에 결제관련 진도가 좀 나가면 또 공유해주세요 ~

**Comment by suncrud** [comment]
잔여이슈 
* 빌링키 DB에 저장후 callback 이 제대로 작동 안하는거 같음. 
* api서버에 post request 아무나 쏠 수 있나..
* 정기결제일에 cronjob 구현

**Comment by woonjjang** [comment]
고생하셨네 ~
@sunparty @mozodev 짧게 콜 해서 callback 문제 해결하고 가면 좋겠습니다. 

[정기결제]
- 사용자 카드 2-3개 payapp에 물려놓고, 10/30일 이나 10/31일 시간을 세밀하게 정해서 결제 떨어지는지 테스트 하면 가장 좋은 상황입니다.

**Comment by mozodev** [comment]
1. [프론트] 빌링키 요청
https://github.com/team-durumi/sooljaru/blob/master/pay-subscription.js#L20

2. [프론트] done에서 api 서버에 빌링키 저장
https://github.com/team-durumi/sooljaru/blob/master/pay-subscription.js#L69

3. [api] 빌링키 정보 저장
https://github.com/team-durumi/sooljaru_api/blob/main/db/schema.rb#L15

4. #2번 done에서 아마도 첫 결제를 요청해야 함.
https://docs.bootpay.co.kr/online/subscript
빌링키로 요청하여 결제하기 (Server SDK / Rest API)
=> 이걸 api 서버에서 해야할 듯..

무슨 콜백을 말씀하시는지? ㅎ

**Comment by mozodev** [comment]
- [ ] [API] 빌링키로 매일 crontab 정기 결제 예약
정기 결제 예약하기 (Server SDK / Rest API)
https://api.bootpay.co.kr/subscribe/billing/reserve (POST)

- [ ] 구독 취소 시 빌링키 삭제 요청
발급된 빌링키 취소하기 (Server SDK / Rest API)
https://api.bootpay.co.kr/subscribe/billing/{biiling_key} ( DELETE )

**Comment by mozodev** [comment]
0. Access Token 발급받기
https://docs.bootpay.co.kr/rest/token 서버에서 각종 요청을 하려면 이거도 해야함...
https://admin.bootpay.co.kr/install/key 여기서 API 서버 아이피도 등록해야 함...

1. api 서버에서 처리
https://github.com/team-durumi/sooljaru/blob/master/pay-subscription.js#L69
프론트에서 부트페이로 직접 요청하지 않고 이것도 api 서버에서 처리한다.

2. 서버 보안
api 서버에 유효하지 않은 빌링키나 기타 시도가 걱정되면 결제 요청하는 ip 대역(cloudflare)을 ec2 security rule 에 등록하거나...
유효한지 판단할 수 있는 데이터 기준을 찾아내거나 만들어서 api validation...
결제 요청을 api 서버에서 하면 더 정확하게 검증가능할 수도...

3. 프론트 보안
https://developers.google.com/recaptcha 추가해서 사람인지는 확인 ㅎ
https://developers.google.com/recaptcha/docs/verify 서버에서 리캡차 통과했는지 확인 가능.

4. 결제 검증하기 (서버)
https://docs.bootpay.co.kr/rest/verify
어차피 만든 빌링키를 넣어봤자.. 우연히 일치해서 결제가 되는 경우를 제외하고는 실제 결제 요청 시 실패...
다만 클라이언트에서는 결제 정보를 조작할 수 있기 때문에 실제 결제가 되기 전에 부트페이에 다시 한번 확인...

**Comment by woonjjang** [comment]
@sunparty 실서버 배포 및 오픈 테스트까지 마치고 이슈를 닫아주세요.
